repos:
  - repo: https://github.com/thlorenz/doctoc
    rev: v1.4.0
    hooks:
      - id: doctoc
        exclude: ^vendor/
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
        exclude: ^vendor/
      - id: go-imports
        exclude: ^vendor/
